### ISSUE TITLE
Some apps crash occasionally

### ISSUE THREAD

**Issue by izardi** [CarbonROM/android_device_sony_poplar#1]
Some applications crash occasionally
Like coolapk
This is the log file that I grab with logcatreader
You can use this software to locate coolapk's error messages
Thank you for your work
[logcat_08-18-2020_11-13-16.txt](https://github.com/CarbonROM/android_device_sony_poplar/files/5088149/logcat_08-18-2020_11-13-16.txt)

[com.dp.logcatapp.apk.zip](https://github.com/CarbonROM/android_device_sony_poplar/files/5088152/com.dp.logcatapp.apk.zip)

**Comment by imrasalghul** [comment]
If you don't mind sending this to support@carbonrom.org
